# DEPLOYMENT FILE --> tells k8s 
#         1. what container image to use
#         2. how many replicas(pods) we want
#         3. how to update the app(rolling updates,restart)
#         4. resources limit, env vars, ports

apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: python
  name: python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python
    spec:
      containers:
      - image: 408595458482.dkr.ecr.us-east-1.amazonaws.com/juhi
        name: juhi
        resources: {}
status: {}
