# A service expose pods so they can be accessed
#   1. inside the cluster
#   2. From outside the cluster
#   3. Via a stable IP and DNS


apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: python
  name: python
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: python
  type: LoadBalancer
status:
  loadBalancer: {}
